### ISSUE TITLE
Levels doesn't  shown in menu on Chrome with FlasHLS playback

### ISSUE THREAD

**Issue by me-vlad** [clappr/clappr-level-selector-plugin#10]
Browser: Chrome 46.0.2490.86 (64-bit)
OS: Fedora 23 x86_64

Clappr Version: 0.2.22

Steps to reproduce:

1 Open FlasHLS test page http://cluster.video/level/flashls.html and start a stream
2 Click on level button - only one field present in menu (AUTO)
3 Seek back or pause dvr stream and click on level button  - all levels present in menu
4 Return to live - all levels present in menu

Level menu works with FlasHLS on Firefox 42 and with hlsjs playback on Chrome
HLSJS test page:
http://cluster.video/level/hlsjs.html

**Comment by me-vlad** [comment]
Same issue with latest Chrome on Android 5.1.1 and on android native browser - only AUTO option present in levels menu

**Comment by ljbitzki** [comment]
In my case, the same happens, but if you click "AUTO option", or stop the live playback and seek a little time in the buffered seekbar and select return to Live, the bitrate list appears!
Tested in: Chrome 46.0.2490.86 m - IE 11.0.10240.16590 and Edge 20.10240.16384.0.

PS.: Firefox 38.4.0 - Work's great.

**Comment by leandromoreira** [comment]
@me-vlad the only problem is related to flashls?

**Comment by me-vlad** [comment]
@leandromoreira  yes, as you can see on my test pages, level selecor menu works with hlsjs but not with flashls
flasHLS: http://cluster.video/level/flashls.html 
HLSJS: http://cluster.video/level/hlsjs.html

**Comment by me-vlad** [comment]
@leandromoreira  and same issue with mpeg-dash (DashShakaPlayback)
http://cluster.video/level/dash.html

**Comment by leandromoreira** [comment]
cool @me-vlad for the dashshaka I think I know what is the problem, I think we need to standardize the way we "list" and "chose" bitrate/levels across the different playbacks

**Comment by flavioribeiro** [comment]
yeah maybe design a protocol for listing/changing levels is the way to go

**Comment by leandromoreira** [comment]
:+1: even better

**Comment by leandromoreira** [comment]
@me-vlad your original issue is easy to fix, [we're iterating](https://github.com/clappr/clappr-level-selector-plugin/blob/master/src/main.js#L75) through the object but it also has `length` as property thus passing `undefined` to [`getDisplayText`](https://github.com/clappr/clappr-level-selector-plugin/blob/master/src/main.js#L155)
