### ISSUE TITLE
What font is the "HD" text. Want to make a 4K etc version

### ISSUE THREAD

**Issue by anesuc** [clappr/clappr-level-selector-plugin#113]
Pretty much the title says it all. I have been trying to figure this out as it seems to be an SVG. Thanks

**Comment by flavioribeiro** [comment]
https://github.com/clappr/clappr-level-selector-plugin/blob/master/src/public/style.scss#L9

**Comment by anesuc** [comment]
Alright cool. Ended up finding another way as well! Thanks. I'll close this.
