### ISSUE TITLE
property 'playback' of undefined w/ clappr 0.2.27

### ISSUE THREAD

**Issue by me-vlad** [clappr/clappr-level-selector-plugin#18]
Clappr 0.2.27 w/  level-selector plugin 0.1.4

Errors in console:
clappr.js:3684 Uncaught TypeError: Cannot read property 'playback' of undefined
clappr.js:8156 Uncaught TypeError: Cannot read property 'settings' of null

Same issue on http://cdn.clappr.io/

**Comment by leandromoreira** [comment]
tha bug is already fixed https://github.com/clappr/clappr-level-selector-plugin/blob/master/src/main.js#L77 I might did something stupid with tags, I'll bump up version try again with 0.1.5

**Comment by me-vlad** [comment]
@leandromoreira  same errors with 0.1.5 and master

**Comment by leandromoreira** [comment]
I identify thanks @me-vlad

**Comment by leandromoreira** [comment]
I think we'll need to listen to `CORE_CONTAINERS_CREATED` and then bind the events.
