### ISSUE TITLE
Buffering animations sometimes never ends

### ISSUE THREAD

**Issue by cowai** [clappr/clappr-level-selector-plugin#22]
Hi,
I have a problem with this plugin where the buffering animations sometimes never goes away when the video is ready and playing.
I have only tested with live stream.

I have only experienced the problem on Firefox (using linux).

Test url:
http://rawgit.com/cowai/b14e3825604c6e612120/raw/a334f3a5774a5313a2447d8c12a10ad95f078406/clappr-live-icon-with-dvr-and-levelselector-test.html

**Comment by leandromoreira** [comment]
Is it easy to reproduce this?

**Comment by cowai** [comment]
Hi,
Yes, just try to skip around in the timeline. For me it happens almost every time I skip.

**Comment by leandromoreira** [comment]
Thanks, this might be a problem with clappr/video5 playback

**Comment by cowai** [comment]
Without this plugin, it never happens though.

**Comment by leandromoreira** [comment]
O.O

**Comment by cowai** [comment]
You can see all the options I use here: http://rawgit.com/cowai/b14e3825604c6e612120/raw/a334f3a5774a5313a2447d8c12a10ad95f078406/clappr-live-icon-with-dvr-and-levelselector-test.html

hls.js is being used.

**Comment by leandromoreira** [comment]
I think I know what it is https://github.com/clappr/clappr-level-selector-plugin/blob/master/src/main.js#L29 we may need to check if [core.isReady](https://github.com/clappr/clappr/blob/master/src/components/core/core.js#L50) to call it directly otherwise listen to the event

**Comment by cowai** [comment]
I dont get this error anymore. Is it fixed?

**Comment by leandromoreira** [comment]
We fixed a lots of things on clappr's side (mostly buffering), i think it's reasonable! can we close this?

**Comment by cowai** [comment]
Yes as I dont experience the problem on latest clappr I think so yes :)

**Comment by leandromoreira** [comment]
lol thanks so much @cowai
