### ISSUE TITLE
How to prevent to click on current list element?

### ISSUE THREAD

**Issue by mikeevstropov** [clappr/clappr-level-selector-plugin#26]
If i click on a current list element before level switch is ended player will die without any errors on console. It looks like a infinite loading. How to prevent click on current list element?

**Comment by hmoraes** [comment]
Hi @mikeevstropov

I made a minor fix in the code to prevent to click on current list element, see [here](https://github.com/hmoraes/clappr-level-selector-plugin/commit/de17fcb828a715d2d496b502872a476dcceef45e)

**Comment by mikeevstropov** [comment]
@hmoraes Thank you friend! I think we need to create a new pull request for it.

**Comment by leandromoreira** [comment]
I agree with @mikeevstropov @hmoraes

**Comment by hmoraes** [comment]
Hi @leandromoreira and @mikeevstropov 

I did the pull request

# # #34
