### ISSUE TITLE
Event error inside the plugin after update on Clappr 0.2.39 (HLS VoD)

### ISSUE THREAD

**Issue by mikeevstropov** [clappr/clappr-level-selector-plugin#28]
Console (clappr.min.js):
```console
Uncaught TypeError: Cannot read property '_listenId' of null
```

Initiator (line 154 on level-selector.js):
```javascript
this.listenToOnce(this.getPlayback(), _Clappr.Events.PLAYBACK_FRAGMENT_LOADED, this.onFragmentLoaded);
```

**Comment by leandromoreira** [comment]
are you using 0.1.8 version? I can't find this code `PLAYBACK_FRAGMENT_LOADED` at it.

**Comment by mikeevstropov** [comment]
@leandromoreira yes, 0.1.8
https://github.com/clappr/clappr-level-selector-plugin/blob/master/dist/level-selector.js#L154

**Comment by leandromoreira** [comment]
@mikeevstropov we're uploaded an old version =/ we need to rebuild a new version

**Comment by mikeevstropov** [comment]
@leandromoreira Ok. =) Thank you for answer!

**Comment by leandromoreira** [comment]
I'm working on this https://github.com/clappr/clappr-level-selector-plugin/issues/24 and if I can get through I'll publish a new version.

**Comment by leandromoreira** [comment]
let's leave this issue open until we see if this is still an issue.

**Comment by mikeevstropov** [comment]
I think we can close this issue.
Clappr 0.2.40 with Level-Selector 0.1.9 work fine.

**Comment by leandromoreira** [comment]
thanks @mikeevstropov
