### ISSUE TITLE
Level doesn't upate automatically by default

### ISSUE THREAD

**Issue by DavidVentura** [clappr/clappr-level-selector-plugin#31]
![vmware1](https://cloud.githubusercontent.com/assets/3650670/13791478/1dde2342-eacc-11e5-8262-ae5766cc4854.png)

When you load the player it start playing the lowest bitrate video by default (for me that's 'Audio') then starts switching to higher-bitrate videos until it reaches high, but the label doesn't update to show this. If I switch manually, the label shows the correct values

**Comment by hmoraes** [comment]
Hi  @DavidVentura 

I made a minor fix in the code to correctly display the level when using Auto, see [here](https://github.com/hmoraes/clappr-level-selector-plugin/commit/88bfecef4531b1ea318547dfadde03cc3436606f)

**Comment by joaopaulovieira** [comment]
Fixed on #34 . Thanks @hmoraes !
