### ISSUE TITLE
Problem switching quality

### ISSUE THREAD

**Issue by uves** [clappr/clappr-level-selector-plugin#33]
The problem occurs with the switching version , the first time a change is made ,
another has not only changes the label , but the quality is not affected.

I use clappr-rtmp-plugin and clappr-level-selector-plugin.

**Comment by zippyDoDat** [comment]
Switching levels throws a TypeError:  this.hls Undefined
the controls text changes, but the video remains in auto mode.

Console from Firefox 42. and 46.0.1 on OSX 10.11.5:

20:02:44.065 TypeError: this.hls is undefined
E</<.set() clappr.min.js:10
d</<.value() level-selector.min.js:7
<anonymous> self-hosted:751
t.fn.on/</u() clappr.min.js:2
s/</i.proxy() clappr.min.js:1
1 clappr.min.js:10:16502

I am using 
https://cdn.jsdelivr.net/clappr/latest/clappr.min.js
https://cdn.jsdelivr.net/clappr.level-selector/latest/level-selector.min.js

and the native clapper hls
plugins: {
            'core': [LevelSelector]
        }

I know for sure this worked a few months ago

**Comment by leandromoreira** [comment]
@zippyDoDat this error was already fixed, did you try with the latest version?
