### ISSUE TITLE
Show level's height (720p, 480p) instead of bitrate

### ISSUE THREAD

**Issue by NicholasAsimov** [clappr/clappr-level-selector-plugin#39]
So I've looked into this thing and it seems that hls.js and flashls have different _fillLevels methods. hls.js is using '${level.bitrate/1000}Kbps' while flashls uses '${levels[index].height}p'. Can we unify them and maybe make them an option to choose between kbps and height.

**Comment by NicholasAsimov** [comment]
It seems that HLS.js playback uses `${level.bitrate/1000}Kbps` format but FlasHLS uses `${levels[index].height}p`. Is there a reason why you can't use it them interchangeably and if there's not maybe we can make it an option?

**Comment by leandromoreira** [comment]
@NicholasAsimov you can name your label as you wish:
```javascript
var player = new Clappr.Player({
  source: "http://your.video/here.m3u8",
  plugins: {
    'core': [LevelSelector]
  },
  levelSelectorConfig: {
    title: 'Quality',
    labels: {
        2: 'High', // 500kbps
        1: 'Med', // 240kbps
        0: 'Low', // 120kbps
    }
  },
});
```
Maybe an interesting thing would be a wrapper/callback for you to label it in runtime.

**Comment by NicholasAsimov** [comment]
Thanks for the answer! This issue can be closed.
