### ISSUE TITLE
Set default resolution and use auto resolution when enter full screen

### ISSUE THREAD

**Issue by kulab45** [clappr/clappr-level-selector-plugin#44]
May I know how to set default resolution? 

I've embedded the very small size player to my website (325x183) but the player always select the best resolution of my streaming to play (720p). So may I ask how to set default resolution to "360p" and when click full screen it'll change to "Auto" resolution by itself.

**Comment by joaopaulovieira** [comment]
I think this case is not the goal of the plugin but is possible to do this with the existing playback properties. The Clappr playbacks that have compatibility with this plugin have the property `currentLevel` and are possible to update via playback instance.

Example of a solution (tested this [code](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cHM6Ly9iaXRkYXNoLWEuYWthbWFpaGQubmV0L2NvbnRlbnQvTUkyMDExMDkyMTAwODRfMS9tM3U4cy9mMDhlODBkYS1iZjFkLTRlM2QtODg5OS1mMGY2MTU1ZjZlZmEubTN1OCcsCiAgcG9zdGVyOiAnaHR0cDovL2NsYXBwci5pby9wb3N0ZXIucG5nJywKICBtdXRlOiB0cnVlLAogIGhlaWdodDogMzYwLAogIHdpZHRoOiA2NDAsCiAgcGx1Z2luczogeyBjb3JlOiBbTGV2ZWxTZWxlY3Rvcl0gfQp9KTsKCnZhciBsZXZlbFdpdGhvdXRGdWxsc2NyZWVuID0gMAoKcGxheWVyLm9uKENsYXBwci5FdmVudHMuUExBWUVSX0ZVTExTQ1JFRU4sIGZ1bmN0aW9uKCkgewogIGNvbnNvbGUubG9nKCdjdXJyZW50IGxldmVsIGJlZm9yZSBmdWxsc2NyZWVuIHRvZ2dsZScsIHBsYXllci5jb3JlLmFjdGl2ZVBsYXliYWNrLmN1cnJlbnRMZXZlbCkKICBwbGF5ZXIuY29yZS5hY3RpdmVQbGF5YmFjay5jdXJyZW50TGV2ZWwgPSBwbGF5ZXIuY29yZS5pc0Z1bGxzY3JlZW4oKSA/IC0xIDogbGV2ZWxXaXRob3V0RnVsbHNjcmVlbgogIGNvbnNvbGUubG9nKCdjdXJyZW50IGxldmVsIGFmdGVyIGZ1bGxzY3JlZW4gdG9nZ2xlJywgcGxheWVyLmNvcmUuYWN0aXZlUGxheWJhY2suY3VycmVudExldmVsKQp9KQoKcGxheWVyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOwoKcGxheWVyLmNvcmUuYWN0aXZlUGxheWJhY2sub24oQ2xhcHByLkV2ZW50cy5QTEFZQkFDS19MRVZFTFNfQVZBSUxBQkxFLCBmdW5jdGlvbihsZXZlbHMpIHsKICBjb25zb2xlLmxvZyhsZXZlbHMpCiAgcGxheWVyLmNvcmUuYWN0aXZlUGxheWJhY2suY3VycmVudExldmVsID0gbGV2ZWxXaXRob3V0RnVsbHNjcmVlbgp9KQ==) on `clappr.io/demo`):
```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  plugins: { core: [LevelSelector] }
});

var levelWithoutFullscreen = 0

player.on(Clappr.Events.PLAYER_FULLSCREEN, function() {
  player.core.activePlayback.currentLevel = player.core.isFullscreen() ? -1 : levelWithoutFullscreen
})

player.attachTo(playerElement);

player.core.activePlayback.on(Clappr.Events.PLAYBACK_LEVELS_AVAILABLE, function(levels) {
  player.core.activePlayback.currentLevel = levelWithoutFullscreen
})
```
