### ISSUE TITLE
wrong switching

### ISSUE THREAD

**Issue by antonzhelyazkov** [clappr/clappr-level-selector-plugin#46]
Hi clappr team,

We have strange problem with level selector. When we start nDVR stream level selector plugin begins switching between 2 profiles in our playlist. If you move scroller backwards and than "back to live" problem disappears. We use Wowza and here is configuration of our smil file:

`<?xml version="1.0" encoding="UTF-8"?>
<smil title="diema">
        <body>
                <switch>
                        <video height="360" src="diema_live.stream"
                systemLanguage="bul" width="640">
                                <param name="videoBitrate" value="650000" valuetype="data"></param>
                                <param name="audioBitrate" value="64000" valuetype="data"></param>
                        </video>
                        <video height="576" src="diema_live_sd2.stream"
                systemLanguage="bul" width="720">
                                <param name="videoBitrate" value="1400000" valuetype="data"></param>
                                <param name="audioBitrate" value="96000" valuetype="data"></param>
                        </video>
                </switch>
        </body>
</smil>`

Here is our playlist file:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=714000,NAME="LQ",CODECS="avc1.100.30,mp4a.40.2",RESOLUTION=640x360
chunklist_w165283381_b714000_slbul_t64TFE=.m3u8?h=KxGjlXd2J
#EXT-X-STREAM-INF:BANDWIDTH=1496000,NAME="HQ",CODECS="avc1.100.30,mp4a.40.2",RESOLUTION=720x576
chunklist_w165283381_b1496000_slbul_t64SFE=.m3u8?h=KxGjlXd2J

I tried to investigate the problem. It seem that clappr gets chunklists for our 2 profiles. When I change the places of our profiles - primary 576p, secondary 360p problem disappears. Could you help me to resolve the problem here is our clappr configuration:

`var playerElement = document.getElementById("player");
  var player = new Clappr.Player({
  source: 'http://xxx.xxx.xxx.xx:80/dvr/test.smil/playlist.m3u8?DVR',
  baseUrl: '/clappr',
  autoPlay: true,
  playbackNotSupportedMessage: "Your browser does not support the playback of this video./n Please try on a different browser or try to install Adobe Flash Player(<a href='https://get.adobe.com/flashplayer'>https://get.adobe.com/flashplayer</a>).",
  mediacontrol: {seekbar: "#4D6EAC", buttons: "#66B2FF"},
        plugins: [LevelSelector],
        levelSelectorConfig: {
        title: 'Quality',
                labels: {
                        2: "HD",
                        1: 'High',
                        0: 'Low',
                },
                labelCallback: function(playbackLevel, customLabel) {
                        return customLabel +'('+ playbackLevel.level.height+'p)';
                }
        },
//  hlsLogEnabled : false,
//  parentId: "#player",
//  hlsMinimumDvrSize: 0,
//startFromLevel: -2,
//autoStartMaxDuration : 1000,
//  flushLiveURLCache : false,
  useHardwareVideoDecoder: true,
//  maxBufferLength: 20,
//  hlsjsConfig: {
//      maxMaxBufferLength: 30,
//      maxLoadingDelay : 2
//  } ,
  mute: false,
  height: 360,
  width:  640
});

player.attachTo(playerElement);`

**Comment by leandromoreira** [comment]
did you watch the network requests? if yes, did you notice if the browser is really doing requests to different playlists? are you able to reproduce this using other [`live hls streaming`](http://g33ktricks.blogspot.com.br/2016/04/list-of-hls-streaming-video-sample-test.html)?

**Comment by antonzhelyazkov** [comment]
Thank you,
Here is a test url with problem stream http://players.neterra.tv:8080/clappr/kinonova.html
Could you try to start stream? If you start network tab you will see what problem I tried to describe.

**Comment by antonzhelyazkov** [comment]
it seems that my problem is connected with wrong stream alignment. My streams are not synchronized.

**Comment by leandromoreira** [comment]
@antonzhelyazkov when you this stream `http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8` does it works just fine?

**Comment by antonzhelyazkov** [comment]
@leandromoreira 
Hi,
It seem that this is server side problem. Could you help me to configure clappr level selector to work only with manual switch between profiles? I want to disable auto switch.

Thank you in advance.

**Comment by leandromoreira** [comment]
@antonzhelyazkov sure, you'll need to fine [tune hls.js](https://github.com/dailymotion/hls.js/blob/master/API.md#quality-switch-control-api) as the author [(@mangui) have stated](https://github.com/dailymotion/hls.js/pull/124#issuecomment-163401802)  : 

>
> you just need to do hls.loadLevel=0 before or just after calling hls.loadSource(url)
this will start from lowest and stick to it (disable autoswitch).
>

You can see more about it on [API documentation](https://github.com/dailymotion/hls.js/blob/master/API.md#hlsloadlevel). And it's easy to integrate this configuration with clappr.
