### ISSUE TITLE
selector-plugin not working 

### ISSUE THREAD

**Issue by shuyabin** [clappr/clappr-level-selector-plugin#47]
see #24  [https://github.com/clappr/clappr-level-selector-plugin/issues/24](url)

**Comment by shuyabin** [comment]
not woking... 
`  <script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/clappr.level-selector/latest/level-selector.min.js"></script>
  <title>clappr-level-selector-plugin Test Page</title>
  <script type="text/javascript" charset="utf-8">
  window.onload = function() {
  var player = new Clappr.Player({
    source: "http://vpls.oss-cn-beijing.aliyuncs.com/page/index/first/%E8%B4%AD%E7%89%A9.mp4", 
    parentId: '#player-wrapper',

    plugins: {
      core: [LevelSelector],
    },
    width: 640, height: 360,
    hideMediaControl: false,
    autoPlay: true
  });
}
  </script>
</head>
<body>
  <div align="center">
    <div id="player-wrapper">
  </div>
  </div>
</body>`

**Comment by shuyabin** [comment]
![image](https://cloud.githubusercontent.com/assets/14884581/21181956/6e912c16-c23b-11e6-8232-7c7f6da828d8.png)

it not working ...  Ask for help.

Thanks

**Comment by leandromoreira** [comment]
@shuyabin does it show any error on console log? (devtool)

**Comment by vxman** [comment]
@shuyabin  , i have also same problem ,pls suggest me the changes.
so that it will work.
@leandromoreira ,it does not  show any error on console log.

**Comment by leandromoreira** [comment]
are you guys using hls stream?

**Comment by vxman** [comment]
@leandromoreira , I am also using live stream and video . suggest me how to use level-selector plugin.

**Comment by leandromoreira** [comment]
are you using hls? (m3u8 or mp4)

**Comment by bulatei** [comment]
@leandromoreira , with mp4 does not work?

**Comment by leandromoreira** [comment]
@bulatei nope, you can implement a custom level selector but this one relies on hls or dash adaptive streaming.
