### ISSUE TITLE
Changing to quality level 0 does not update text properly

### ISSUE THREAD

**Issue by slhck** [clappr/clappr-level-selector-plugin#5]
In the `updateText(level = undefined)` function, the check shouldn't be
```
if (!level) {
```

but probably

```
if (level === undefined) {
```

Otherwise, level 0 (because it's `false`) will not cause the label for level 0 to render correctly.

**Comment by towerz** [comment]
@slhck already changed this, but this check will only make `level` be reassigned to the current level, and the text will render correctly anyway.

There was another problem that was causing the levels to not render correctly (#3).
