### ISSUE TITLE
Does clappr selector still working ?

### ISSUE THREAD

**Issue by Tilkeii** [clappr/clappr-level-selector-plugin#63]
I'm using clappr with m3u8 playlist and clappr-level-selector-plugin
 doesn't work. I have the same code as the exemple. There is no error in console and clappr work fine

```javascript
var player = new Clappr.Player({
	source: "http://192.168.1.23:8080/hls/test/index.m3u8",
	parentId: "#player",
	plugins: {
		'core': [LevelSelector]
	},
	levelSelectorConfig: {
		title: 'Quality',
		labels: {
			2: 'High', // 500kbps
			1: 'Med', // 240kbps
			0: 'Low', // 120kbps
		},
		labelCallback: function(playbackLevel, customLabel) {
			return customLabel + playbackLevel.level.height+'p'; // High 720p
		}
	},
});
```

**Comment by leandromoreira** [comment]
can you test with:

```javascript
var player = new Clappr.Player({
	source: "http://192.168.1.23:8080/hls/test/index.m3u8",
	parentId: "#player",
	plugins: [LevelSelector]
 });
```

**Comment by Tilkeii** [comment]
It doesn't work neither. Still 0 error and clappr working well but not the plugin

**Comment by leandromoreira** [comment]
Hi @Tilkeii 

I tested here and it's working fine, try for yourself:

* Go to http://clappr.io/demo/
* Fill the input `Add external plugins` with http://cdn.jsdelivr.net/gh/clappr/clappr-level-selector-plugin@latest/dist/level-selector.min.js
* Add the following code

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'https://video-dev.github.io/streams/x36xhzz/x36xhzz.m3u8',
  poster: 'http://clappr.io/poster.png',
  plugins: [LevelSelector],
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);

```

* Click on `[Run]`


![screen shot 2018-01-29 at 4 23 02 pm](https://user-images.githubusercontent.com/55913/35527178-0e36774e-0511-11e8-9af9-b175ae6df98a.png)

**Comment by Tilkeii** [comment]
Oh i think i find the problem. I tested with the configuration i had but with your source link (https://video-dev.github.io/streams/x36xhzz/x36xhzz.m3u8) and it work. I think adding port break the plugin

**Comment by leandromoreira** [comment]
Maybe it's related to your hls stream, does it have multiple renditions?

**Comment by Tilkeii** [comment]
I use nginx-rtmp-module and i have only 1 simple application

```
rtmp {
	server {
		listen 1935;
		ping 30s;
		notify_method get;
		
		application hls {
			live on;
			max_connections 1;
			
			hls on;
			hls_path /usr/local/nginx/html/hls;
			hls_nested on;
		}
	}
}
```

**Comment by Tilkeii** [comment]
Oh i think i get it. I'll try to fix my HLS stream
