### ISSUE TITLE
Please publish this package on npm registry

### ISSUE THREAD

**Issue by paluh** [clappr/clappr-level-selector-plugin#64]
I'm not able to find this package in npm. Is it published? If not could you please publish it?

**Comment by mmjjb** [comment]
Any updates?

**Comment by mmjjb** [comment]
Try this
`npm i clappr/clappr-level-selector-plugin --save`

After that you will find it in folder 'level-selector'

**Comment by towerz** [comment]
https://www.npmjs.com/package/level-selector
