### ISSUE TITLE
cannot use level selector plugin with lastest clappr 

### ISSUE THREAD

**Issue by phamvinhthanh** [clappr/clappr-level-selector-plugin#7]
Dear Towerz,

I cannot use this plugin with lastest clappr. I remember I can use it 1 month ago. My console shows "Uncaught ReferenceError: external undefined plugin on core array".

My test link is: http://203.162.56.33:9000/jshls/test.html

Best regards,

**Comment by ChiliChili** [comment]
Hi!

Same problem here. I've tried the self-hosted, and CDN version, but don't work, dont see the auto option. The m3u8 HLS stream linking, four qualities sub m3u8 stream.
The HLS stream works fine on windows Chrome and OS X Safari/Chrome.

Head:

    <script type="text/javascript" src="/clappr/dist/clappr.min.js"></script>
    <script type="text/javascript" src="/clappr/dist/level-selector.min.js"></script>

Body:

    <script>
    var player = new Clappr.Player({
	    source: "http://ip/live/stream.m3u8",
		    parentId: "#player",
			plugins: {
			  'core': [LevelSelector]
			},
			mediacontrol: {seekbar: "#ff0000", buttons: "##b7c9d8"},
			autoPlay: true,
			height: 540,
			width: 960,
			disableVideoTagContextMenu: true,
			pause: true
		});
	</script>

**Comment by towerz** [comment]
@phamvinhthanh @ChiliChili the plugin has already been updated to version 0.1.0 to work with the latest version of Clappr (0.2.18). The problem is that jsdelivr sometimes take too long to update the `/latest` url. Try using http://cdn.jsdelivr.net/clappr.level-selector/0.1.0/level-selector.min.js instead. It should work with your sample.

**Comment by towerz** [comment]
@ChiliChili are you using the latest version of Clappr? The plugin didn't work with the default HLS playback on previous versions of Clappr. It has been since updated to trigger the events that enabled level switching on the hls.js playback.

**Comment by ChiliChili** [comment]
@towerz thank you to tell me, was the ver. 0.2.15 in use... Great plugin!
Works fine on Windows: Chrome/Firefox 41.0 and on Ubuntu 14.04 Chrome
Os X 10.11.1  Safari 9.0.1 player works, but only Auto option loaded.
Os X 10.11.1  Chrome working good
Thx!

**Comment by towerz** [comment]
@ChiliChili Safari in fact is not supported, since HLS is loaded using the video tag directly, and there's no api to change levels natively. The plugin only works when either the HLS or the FlasHLS playback is loaded.

I'll add a check to not display the menu when there's only the `Auto` option to avoid misleading.

**Comment by ChiliChili** [comment]
@towerz I understand and I'm not happy. How to operate with Safari? Possible?

**Comment by phamvinhthanh** [comment]
@towerz :+1: working for me

**Comment by towerz** [comment]
@ChiliChili as it was discussed previously on Clappr issues, the only way to support manual quality changes is using the FlasHLS playback. The MSE-based HLS playback doesn't work correctly on Safari, so it's disabled by default.

To force using FlasHLS, you can just pass this on player instantiation:
```javascript
plugins: {
  core: [LevelSelector],
  playback: [Clappr.FlasHLS]
}
```
This will work on Safari as you wanted.

**Comment by cowai** [comment]
Why could we not just set the source of the player to a level directly?  That would work in all browsers.
