### ISSUE TITLE
FR: add possibility to invert resolutions

### ISSUE THREAD

**Issue by Niko78** [clappr/clappr-level-selector-plugin#84]
hi,
Right now the plugin displays values from bottom to top
That would be interesting to get values inverted : 
Quality
AUTO
1080p
720p
360p

instead of
Quality
AUTO
360p
720p
1080p

thanks

Nico

**Comment by kslimani** [comment]
I think it is easy to solve, for example adding a new `onLevelsAvailable` configuration  option which accept a "transform" function as value.

Usage example :

```javascript
var player = new Clappr.Player({
  // [...]
  levelSelectorConfig: {
    onLevelsAvailable: function(levels) {
      // here do whatever you want (filter, sort, etc...)
      return levels
    },
  },
});
```

**Comment by leandromoreira** [comment]
i think you can mix them togheter
